export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SEARCH_CITIES_REQUEST = 'SEARCH_CITIES_REQUEST';
export const SEARCH_CITIES_SUCCESS = 'SEARCH_CITIES_SUCCESS';
export const SEARCH_CITIES_FAILURE = 'SEARCH_CITIES_FAILURE';
export const RESET_SEARCH = 'RESET_SEARCH';